events {}

http {

    sendfile on;
    tcp_nopush on;

    server {

        listen 8151;

        location / {

            root /hls;

            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            add_header Cache-Control no-cache;
        }
    }
}